version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: apimanager-postgres-dev
    environment:
      POSTGRES_DB: apimanager
      POSTGRES_USER: apimanager_user
      POSTGRES_PASSWORD: apimanager_password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - apimanager-network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: apimanager-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - apimanager-network
    restart: unless-stopped

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  apimanager-network:
    driver: bridge 